- name: install nginx
  pacman: name=nginx state=present
- name: install nginx.conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
- name: nginx start
  systemd:
    name: nginx
    state: started
    enabled: True
