- hosts: all
  user: ansible
  become: yes
  tasks:
    - name: install sbcl
      pacman: name=sbcl state=present

    - name: install all
      pacman: name={{ item }} state=installed
      with_items:
        - vim
        - zsh
        - git
