- hosts: all
  user: ansible
  become: yes
  roles:
    - nginx
    - mariadb
    - postfix
  tasks:
    - name: install all
      pacman: name={{ item }} state=installed
      with_items:
        - vim
        - zsh
        - git
