- hosts: all
  user: ansible
  become: yes
  roles:
    - nginx
    - mariadb
    - postfix
    - vim
    - zsh
    - git
  tasks:
    - name: install all
      pacman: name={{ item }} state=installed
      with_items:        
        - bash-completion
        - zsh-completions
        - tig
        - wget
        - htop
        - rsync
        - tmux
