- name: install mariadb
  pacman: name=mariadb state=present
  when: ansible_os_family == 'Archlinux'
- name: deploy my.conf
  copy:
    src: my.conf
    dest: /etc/mysql/my.cnf
- name: systemctl enable mariadb
  systemd:
    name: mariadb
    state: started
    enabled: True
